export const RISK_WEIGHTS = {
  BASE_SCORE: 10,
  HIGH_AMOUNT_THRESHOLD: 10000000,
  MEDIUM_AMOUNT_THRESHOLD: 5000000,
  LOW_AMOUNT_THRESHOLD: 1000000,
  CRITICAL_AMOUNT_WEIGHT: 40,
  HIGH_AMOUNT_WEIGHT: 25,
  MEDIUM_AMOUNT_WEIGHT: 10,
  UNVERIFIED_KYC_WEIGHT: 20,
  FAILED_ATTEMPT_WEIGHT: 10,
  MAX_FAILED_ATTEMPT_WEIGHT: 30,
  CROSS_BORDER_WEIGHT: 15,
  VPN_WEIGHT: 20,
  UNTRUSTED_DEVICE_WEIGHT: 15,
  IMPOSSIBLE_TRAVEL_WEIGHT: 35,
  BEHAVIOR_NIGHT_ACTIVITY: 10,
  BEHAVIOR_NEW_BENEFICIARY: 15
};
